name: Upload reports to codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install coverage
        run: pip install coverage
      - name: Run tests and collect coverage
        run: |
          coverage run -m unittest
          coverage xml -o reports/test_report.xml
      - name: Upload tests coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./reports/test_report.xml
          fail_ci_if_error: true
        
